name: TheHunters
version: 0.1
author: iHDeveloper
main: me.ihdeveloper.thehunters.Main

commands:
  forcestart:
    usage: "forcestart [countdown]"
    aliases: [ "fs" ]
    description: "Force start the game countdown"
    permission: "thehunters.forcestart"
    permission-message: "You don't have the permission to force start the game countdown"
  setlobbyspawn:
    usage: "setlobbyspawn"
    aliases: []
    description: "Sets location for the players to spawn when the game didn't start yet"
    permission: "thehunters.spawn.lobby"
    permission-message: "You don't have the permission to do this command!"
